# Python Review

Goals:
- Recall basic Python vocabulary
- Practice Markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific task in our programs.

**NumPy**:
- Core library for numerical computing in Python
- Many other libraries use NumPy arrays as builing blocks
- Computations on NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreiation**

In [1]:
import numpy as np

## Variables

**variable**: A name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable a
a = np.array([[1, 1, 2], [3, 5, 8]])

In [3]:
# Run Cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use 'print' function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: Data frame

Properties: Number rows, names of the columns, data created

Actions: Selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variable and object interchangeably.