# Python Review

Goals:
- Recall basic Python vocabulary
- Practice Markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific task in our programs.

**NumPy**:
- Core library for numerical computing in Python
- Many other libraries use NumPy arrays as builing blocks
- Computations on NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreiation**

In [1]:
import numpy as np

## Variables

**variable**: A name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable a
a = np.array([[1, 1, 2], [3, 5, 8]])

In [3]:
# Run Cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use 'print' function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: Data frame

Properties: Number rows, names of the columns, data created

Actions: Selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variable and object interchangeably.

## Types

Every object in Python has a **type**. The type tells us what kind of object it is.

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have.

In [5]:
print(a)

# Check the type / class of a variable / object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [6]:
print(a[0, 0])

# Check the type on an entry on the array by indexing
type(a[0, 0])

1


numpy.int64

Notice that `type(a[0, 0])` is `numpy.int64` and not just the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number.

In [7]:
print(a[1, 1])

5


## Functions

`print` was our first example of a Python **function**.

Functions take in a set of **arguments** and those arguments create an **output**.

argument = parameter.

We can ask information about a function by executing `?function`

In [8]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two types of arguments.

- **non-optional argument**: arugments *you* need to specify for the function to do something

- **optional argument**: arguments that are pre-filled with a default value by the function. You can override them. Optional arguments appear inside the paraenthesis in the form `optional_argument = fault_value`

In [9]:
print('changing the default end argument', end = ' :)')

changing the default end argument :)

## Attributes & Methods

An object in Python has attributes and methods.

- **attribute**: a property of an object, some piece of information about it
- **method**: a procedure associated with the object, an action where the main ingredient is the object.

### Check-in

Fish attriutes:

- length, color, species
- die(), bite(), swim()

**Example**
Attributes for `numpy.arrays`

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name.

`variable.method()` or `variable.attribute'

In [10]:
a.shape

(2, 3)

In [11]:
type(a.shape)

tuple

In [12]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis = 0)

array([1, 1, 2])

## Check-in

We can also call the `min` method without any parameter:

In [14]:
a.min()

1

Remember: Methods are functions associated with an object. 

In [15]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the **type** of the argument `sep`? Is this a optional or non-optional argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variable to print `77%99%77` by changing the value of one of the optional arguments in `print`.

In [17]:
var77 = 77

var99 = '99'

print(var77, var99, var77, sep = '%')

77%99%77


## Check-in 1

1. The integer number `-999` is often used to represent missing values. Create a pandas.Series named `s` with four integer values, two of which are `-999`. The index of this series should be the letters A through D.

2. In the pandas.Series ?documentation, look for the method `mask()`. Use this method to update the series `s` so that the `-999` values are replaced by NA values. HINT: Check the first example in the method's documentation.

In [14]:
# Import required libraries
import pandas as pd
import numpy as np

# Create pandas.Series
s = pd.Series([12, -999, 45, -999], index = ['A', 'B', 'C', 'D'])
print(s)
print(type(s))

A     12
B   -999
C     45
D   -999
dtype: int64
<class 'pandas.core.series.Series'>


In [15]:
s

A     12
B   -999
C     45
D   -999
dtype: int64

In [18]:
s.mask(s == -999, inplace = True)

In [19]:
s

A    12.0
B     NaN
C    45.0
D     NaN
dtype: float64

In [7]:
# Check `mask` documentation

# Mask -999 values in s with default NaN value
s = s.mask(s == -999)

## Check-in 2

We can access the dataframe's column names via the `columns` attribute. Update the column names to C1 and C2 by updating this attribute.

In [9]:
# Make dataframe

d = {'col_name_1' : pd.Series(np.arange(3)),
    'col_name2' : pd.Series([3.1, 3.2, 3.3])}

df = pd.DataFrame(d)

df

col_name_1  col_name2
0           0        3.1
1           1        3.2
2           2        3.3

In [12]:
# Use .columns attribute to rename columns
df.columns = ['C1', 'C2']
df

C1   C2
0   0  3.1
1   1  3.2
2   2  3.3